
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND FALSE NOT OR PARENTESIS_DERECHO PARENTESIS_IZQUIERDO TRUEexpresion : NOT expresionexpresion : expresion AND expresionexpresion : expresion OR expresionexpresion : PARENTESIS_IZQUIERDO expresion PARENTESIS_DERECHOexpresion : TRUEexpresion : FALSE'
    
_lr_action_items = {'NOT':([0,2,3,6,7,],[2,2,2,2,2,]),'PARENTESIS_IZQUIERDO':([0,2,3,6,7,],[3,3,3,3,3,]),'TRUE':([0,2,3,6,7,],[4,4,4,4,4,]),'FALSE':([0,2,3,6,7,],[5,5,5,5,5,]),'$end':([1,4,5,8,10,11,12,],[0,-5,-6,-1,-2,-3,-4,]),'AND':([1,4,5,8,9,10,11,12,],[6,-5,-6,6,6,6,6,-4,]),'OR':([1,4,5,8,9,10,11,12,],[7,-5,-6,7,7,7,7,-4,]),'PARENTESIS_DERECHO':([4,5,8,9,10,11,12,],[-5,-6,-1,12,-2,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,2,3,6,7,],[1,8,9,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> NOT expresion','expresion',2,'p_expresion_not','parsers1.py',34),
  ('expresion -> expresion AND expresion','expresion',3,'p_expresion_and','parsers1.py',38),
  ('expresion -> expresion OR expresion','expresion',3,'p_expresion_or','parsers1.py',42),
  ('expresion -> PARENTESIS_IZQUIERDO expresion PARENTESIS_DERECHO','expresion',3,'p_expresion_parentesis','parsers1.py',46),
  ('expresion -> TRUE','expresion',1,'p_expresion_true','parsers1.py',50),
  ('expresion -> FALSE','expresion',1,'p_expresion_false','parsers1.py',54),
]
